### PR TITLE
Add feedback by Melroy

### PR DESCRIPTION
**Pull request by melroy89**
See my cite.

### CODE REVIEW

**Comment by bitjson** [comment]
Fantastic, thanks for the statement! 

Just to clarify – you added your statement under the `Approve` heading (and it's very positive!), but the statement doesn't explicitly mention "support", "approve", or "recommend" with regard to activating this proposal in 2025. 

Would you mind clarifying in the statement if you support activation in 2025? If you prefer not to take a position on an activation timeline, you can also just move this statement as-is under `Neutral`. Thanks!

**Comment by melroy89** [comment]
> Fantastic, thanks for the statement!
> 
> Just to clarify – you added your statement under the `Approve` heading (and it's very positive!), but the statement doesn't explicitly mention "support", "approve", or "recommend" with regard to activating this proposal in 2025. 
> 
> Would you mind clarifying in the statement if you support activation in 2025? If you prefer not to take a position on an activation timeline, you can also just move this statement as-is under `Neutral`. Thanks!

AH clear. Since I understand what I don't know (aka the lack of knowing the technical details), I move it to Neutral.

**Comment by bitjson** [comment]
Hey @melroy89, thanks again for the PRs! (Here and https://github.com/bitjson/bch-bigint/pull/10)

I'd like to pull these in soon, but they're written in a sort of informal/tentative style (`_Disclaimer:_ I didn't yet run production or load testing with the latest CHIPs. If I find any regression, I will report it via GitLab / Slack.`)

Are you finished with your review? Do you plan to update these statements any more? 

No rush if you plan to continue reviewing, and feel free to continue updating until Nov 14.

**Comment by melroy89** [comment]
Please merge.

**Comment by bitjson** [comment]
Merged, thanks!

**Pull request merged**
